// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for web - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgB-SELnkvfW9zMjcgm6DkhY3tCgtA8U8',
    appId: '1:350828450571:android:7829b7c4145cd123e7480e',
    messagingSenderId: '350828450571',
    projectId: 'fren-9cc3c',
    storageBucket: 'fren-9cc3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdmC-TiOOdABZzZyOmK4tVnj8CtTiyRDE',
    appId: '1:350828450571:ios:17294882ee8fc53be7480e',
    messagingSenderId: '350828450571',
    projectId: 'fren-9cc3c',
    storageBucket: 'fren-9cc3c.appspot.com',
    androidClientId:
        '350828450571-33s9lbm7rnt6mfteu6u46lbr99c1qh98.apps.googleusercontent.com',
    iosClientId:
        '350828450571-tej1jo4ofag50cq36q1l5kp1750q6qpb.apps.googleusercontent.com',
    iosBundleId: 'app.machi',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBdmC-TiOOdABZzZyOmK4tVnj8CtTiyRDE",
      authDomain: "fren-9cc3c.firebaseapp.com",
      projectId: "fren-9cc3c",
      storageBucket: "fren-9cc3c.appspot.com",
      messagingSenderId: "350828450571",
      appId: "1:350828450571:web:ac7501535080147ee7480e",
      measurementId: "G-DE4RCBCV14");
}
